name: restaurant_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.3
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  firebase_auth: ^5.5.2
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_intelligence_sign3: ^1.0.7

  flutter_localization: ^0.3.2
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_rating_bar: ^4.0.1
  flutter_stripe: ^11.4.0
  flutter_svg: ^2.0.17
  geolocator: ^13.0.4
  google_sign_in: ^6.3.0
  http: 1.3.0
  # intl: ^0.20.2
  latlong2: ^0.9.1
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/category1.png
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
flutter_intl:
  enabled: true
