// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXEQhdNyJkZpliy0V4AJQoxYOh13KEgJg',
    appId: '1:876611807213:web:0504918304d5497302a9e4',
    messagingSenderId: '876611807213',
    projectId: 'fierfier',
    authDomain: 'fierfier.firebaseapp.com',
    databaseURL: 'https://fierfier-default-rtdb.firebaseio.com',
    storageBucket: 'fierfier.appspot.com',
    measurementId: 'G-6801F058SS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMplZumLtVe-kfVVWNWXt6dGPa38zFhSc',
    appId: '1:876611807213:android:41e3b8d23674713e02a9e4',
    messagingSenderId: '876611807213',
    projectId: 'fierfier',
    databaseURL: 'https://fierfier-default-rtdb.firebaseio.com',
    storageBucket: 'fierfier.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBblQcMJZf91P8MxMJAx7FH88aWqh4muss',
    appId: '1:876611807213:ios:e226c6f7f204777202a9e4',
    messagingSenderId: '876611807213',
    projectId: 'fierfier',
    databaseURL: 'https://fierfier-default-rtdb.firebaseio.com',
    storageBucket: 'fierfier.appspot.com',
    iosBundleId: 'com.example.restrantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa4Za5sgY2v3QQW4wc0NA944yVC-1Wwss',
    appId: '1:876611807213:web:a38a3a7d2f77d68802a9e4',
    messagingSenderId: '876611807213',
    projectId: 'fierfier',
    authDomain: 'fierfier.firebaseapp.com',
    databaseURL: 'https://fierfier-default-rtdb.firebaseio.com',
    storageBucket: 'fierfier.appspot.com',
    measurementId: 'G-PV0KZL4MWY',
  );
}
